### ISSUE TITLE
Log deprecation warning should only be printed once

### ISSUE THREAD

**Issue by jorng** [gobuffalo/pop#241]
## Description

When running a buffalo app with the latest version of Pop, the following line is outputted in logs repeatedly:

```
Warning: Log is deprecated, and will be removed in a future version. Please use SetLogger instead.
```

This warning does not indicate where it is coming from, and is repeated over and over again.

### Steps to Reproduce the Problem

  1. Create an app using Buffalo v0.12.6
  1. Install the latest version of pop (via `go get` or `dep`)
  1. Run the application

### Expected Behavior

Deprecation warning should be issued only once, and should have some indication of where it is coming from (what package).

### Actual Behavior

Logs are littered with the same warning message over and over

### Info

Occurs during local dev (macOS 10.14), and in Docker container (debian based)
Buffalo v0.12.6
Pop v4.7.2

```toml
[[constraint]]
  name = "github.com/gobuffalo/buffalo"
  version = "0.12.6"

[[constraint]]
  name = "github.com/gobuffalo/pop"
  version = "4.7.2"
```
