### ISSUE TITLE
Create not persisting the object to the database?

### ISSUE THREAD

**Issue by dosaki** [gobuffalo/pop#291]
I'm trying to get a basic model persisted into my dev database (mariadb).

This is the code that I am having a problem with:
```go
tx, ok := c.Value("tx").(*pop.Connection)
company := models.Company{}
company.Name = "Company A"
if ok {
    fmt.Println(tx.Create(&company)) // Returns nil
}
```
The code runs through ok without reporting any errors:
```
DEBU[2018-11-05T15:27:30Z] INSERT INTO companies (created_at, id, name, updated_at) VALUES (:created_at, :id, :name, :updated_at)
<nil>
```
However when I query the database (both via pop as well as using the mysql client) there's nothing in `companies`.

The `Company` model is defined as below:
```go
type Company struct {
	ID        uuid.UUID `json:"id" db:"id"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
	Name      string    `json:"name" db:"name"`
}
```

And my `database.yml`:
```yml
development:
  dialect: "mysql"
  database: "db_dev"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "passwordhere"
  encoding: "utf8mb4_general_ci"

```
