### ISSUE TITLE
Unable to connect with cockroachdb

### ISSUE THREAD

**Issue by evalsocket** [gobuffalo/pop#513]
## Description 

Pop is unable to connect cockroach DB  when `sslmode is disable`  

connection uri -> `cockroach://root@localhost:26257/defaultdb?sslmode=disable`

The error we are getting -> 

`error=" could not open database connection: pq: SSL is not enabled on the server"`

We are running a server with insecure mode (docker-compose)
``` 
 cockroach:
    image: cockroachdb/cockroach:v1.1.1
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - "./cockroach-data/roach1:/cockroach/cockroach-data"
    command: start --insecure
```
